language: python
env:
    global:
        - OSX_PYTHON_VERSIONS=2.7 3.4 3.5
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          python: 2.7
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        # Use generic language for osx
        - os: osx
          language: generic

# Setup anaconda
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then PYTHON_VERSIONS=$TRAVIS_PYTHON_VERSION ; curl http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -o miniconda.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PYTHON_VERSIONS=$OSX_PYTHON_VERSIONS; curl https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh ; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda


  # Useful for debugging any issues with conda
  - conda info -a

# Install packages
install:
  # scipy and pandas are required by the package 'statsmodels'
  - for VERSION in $PYTHON_VERSIONS ; conda create --name $VERSION --yes python=VERSION --file requirements.txt ; source activate $VERSION ; python setup.py install; fi

# command to run tests
script:
  - for VERSION in $PYTHON_VERSIONS ; source activate $VERSION ; make test; fi

sudo: false

